repos:
- repo: local
  hooks:
  - id: jupytext-sync
    name: Jupytext sync
    entry: jupytext --sync **/*.ipynb
    language: python
    language_version: python 3.13
    types: [jupyter, markdown]
    additional_dependencies: [jupytext]