repos:
- repo: local
  hooks:
  - id: jupytext-sync
    name: Jupytext sync
    entry: jupytext --sync
    language: python
    language_version: python 3.13
    files: \.(ipynb)$
    additional_dependencies: [jupytext]