name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: python -m pip install pre-commit
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: pre-commit run --from-ref origin/main --to-ref HEAD --show-diff-on-failure --color=always
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()